### ISSUE TITLE
Error messages could be more verbose

### ISSUE THREAD

**Issue by valentine** [GIANTCRAB/hsg-label-printer#4]
I tried sending a PDF to the A4 black and white printer, only to receive this message.

I have checked that Power Saver mode is not on on the printer, and sending to it directly over network works.

<img width="749" alt="Screenshot 2022-05-07 at 11 38 02 PM" src="https://user-images.githubusercontent.com/676061/167261409-bdb59855-db37-40e7-97b6-8495be8ec431.png">

**Comment by valentine** [comment]
Couldn't send PDFs to label printer either. Tried power cycling and it didn't work.

**Comment by GIANTCRAB** [comment]
Could you please attach the file here as reference?

Thanks!

Best Regards,
Woo Huiren

"I don't know about you people, but I don't want to live in a world where
someone else makes the world a better place better than we do. " - Gavin
Belson

https://twitter.com/woohuiren

**Comment by valentine** [comment]
[Aircon Dripping.pdf](https://github.com/GIANTCRAB/hsg-label-printer/files/8646080/Aircon.Dripping.pdf)

**Comment by GIANTCRAB** [comment]
Thanks. Fixed in 899156f40dc834378172accd6c9f7a273c04d8a8 and ba0bf713d39cbcec7de0503884fe69b8a1474ecf
